version: "3"

services:
  api:
    build: .
    hostname: ig-scraper-guest
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    restart: always
    networks:
      - main_network

networks:
  main_network:
    external: true
